baseURL = 'https://cambron.cc'
enableEmoji = true
languageCode = 'en-us'
title = 'cambron.cc'
tableOfContents = true
# 1. EXPLICITLY IMPORT THE MODULE
[module]
  imports = [
    {path = 'github.com/adityatelange/hugo-PaperMod'}
  ]

# ----------------------------------------------------
# 1. TAXONOMIES: Define 'category' and 'tag' for grouping content.
# ----------------------------------------------------



[params]
  env = "production"
  defaultTheme = "light" # or "dark"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButton = true
  
  # Set the home page header:
  homeInfoParams.Title = "Andrew Cambron's Homepage"
  homeInfoParams.Content = "The smile you send out comes back to you."

[params.assets]
  disableHLJS = true # Disable Highlight.js if you use default Hugo Chroma
  disableScrollBarStyle = true

[params.socialIcons]
  # Add your social links (e.g., GitHub, LinkedIn, etc.)
  # Example: {name = "github", url = "[https://github.com/ajcambron](https://github.com/ajcambron)"}

# === Menu Links ===
[[menu.main]]
  name = "About"
  url = "about/"
  weight = 10
[[menu.main]]
  name = "Recipes"
  url = "recipes/"
  weight = 20
[[menu.main]]
  name = "Teaching"
  url = "teaching/"
  weight = 30

[permalinks]
	note = '/note/:year/:month/:day/:slug/'
	posts = '/posts/:year/:month/:day/:slug/'


[params.footer]
  footer = "&copy; [andrew](https://cambron.cc) 2020- {Year} -- All rights reserved."

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
