baseURL = 'https://cambron.cc'
enableEmoji = true
languageCode = 'en-us'
title = 'cambron.cc'
tableOfContents = true
# 1. EXPLICITLY IMPORT THE MODULE
[module]
  imports = [
    {path = 'github.com/adityatelange/hugo-PaperMod'}
  ]




[params]
  env = "production"
  defaultTheme = "light" # or "dark"
  disableThemeToggle = true

  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButton = true
  
[params.profileMode]
    enabled = true
    title = "Cambron.cc" # optional default will be site title
    subtitle = "Make, Teach, Understand"
    imageUrl = "/images/cambron/Cambronhead.png" # optional
    imageTitle = "Portrait of Andrew" # optional
    imageWidth = 120 # custom size
    imageHeight = 120 # custom size

    # 'buttons' is an array of tables in YAML, so it becomes an array of tables in TOML
  [[params.profileMode.buttons]]
      name = "Projects"
      url = "/Projects"
 
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/blog"
      
	[[params.profileMode.buttons]]
      name = "Weakfish"
      url = "http://weak.fish"


  # 'socialIcons' is also an array of tables
[[params.socialIcons]] # Notice the double brackets for an array entry
    name = "email"
    url = "mailto:webcontact@weak.fish"
    
  [[params.socialIcons]]
    name = "vimeo"
    url = "https://vimeo.com/cambron"

	[[params.socialIcons]]
    name = "youtube"   
    url = "https://www.youtube.com/@AndrewCambronIsReal"
    
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ajcambron"

[params.assets]
  disableHLJS = true # Disable Highlight.js if you use default Hugo Chroma
  disableScrollBarStyle = true


# === Menu Links ===
[menu]
 [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10
[[menu.main]]
  name = "About"
  url = "about/"
  weight = 20
[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 30
[[menu.main]]
  name = "Projects"
  url = "projects/"
  weight = 35
[[menu.main]]
  name = "Blog"
  url = "blog/"
  weight = 40

[permalinks]
	note = '/note/:year/:month/:day/:slug/'
	posts = '/posts/:year/:month/:day/:slug/'



[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
