name: CommitWebSite
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          # Enable submodule fetching for module cache dependencies, using the default approach
          submodules: true 
          fetch-depth: 0

      # Note: We rely on Hugo Modules to fetch PaperMod, so we removed the manual git submodule commands.
          
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # CRITICAL FIX: Update to a version that supports PaperMod (Min 0.146.0)
          hugo-version: "0.151.0"
          # Ensure the extended version is used, as required for SCSS/PaperMod styling
          extended: true
          
      - name: Build
        # Explicitly telling Hugo where to find the config file
        run: hugo --config hugo.toml --minify
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO }}
          external_repository: ajcambron/ajcambron.github.io
          publish_dir: ./public
          keep_files: true
          user_name: ajcambron
          user_email: ajcambron@gmail.com
          publish_branch: main
          cname: cambron.cc
